import type { KitchenOrder } from "./types";

export const KITCHEN_MOCK_ORDERS: KitchenOrder[] = [
  {
    id: "ko-1042",
    number: "#1042",
    status: "in_preparation",
    priority: "high",
    channel: "table",
    station: "grill",
    tableNumber: "7",
    elapsedMinutes: 14,
    slaMinutes: 18,
    receivedAt: "10:01",
    assignedTo: "Camila",
    items: [
      {
        id: "i1",
        quantity: 2,
        name: "Hamburguesa Bocao",
        modifiers: ["Sin cebolla", "Extra queso"],
      },
      { id: "i2", quantity: 1, name: "Papas grandes" },
      { id: "i3", quantity: 1, name: "Limonada" },
    ],
    kitchenNotes: "Entregar todo junto.",
    timeline: [
      { time: "10:01", titleKey: "eventReceived", channel: "table" },
      { time: "10:03", titleKey: "eventAssigned", actor: "Parrilla" },
      { time: "10:04", titleKey: "eventStarted", actor: "Camila" },
    ],
  },
  {
    id: "ko-1043",
    number: "#1043",
    status: "received",
    priority: "normal",
    channel: "whatsapp",
    station: "sushi",
    customerName: "Martín Vega",
    elapsedMinutes: 3,
    slaMinutes: 22,
    receivedAt: "10:12",
    items: [
      {
        id: "i1",
        quantity: 1,
        name: "Combo Sushi 24 pzas",
        modifiers: ["Sin wasabi extra"],
        allergens: ["Pescado", "Soja"],
      },
      { id: "i2", quantity: 2, name: "Edamame" },
    ],
    timeline: [{ time: "10:12", titleKey: "eventReceived", channel: "whatsapp" }],
  },
  {
    id: "ko-1044",
    number: "#1044",
    status: "delayed",
    priority: "delayed",
    channel: "delivery",
    station: "fryer",
    customerName: "Ana Ríos",
    elapsedMinutes: 28,
    slaMinutes: 20,
    receivedAt: "09:47",
    assignedTo: "Diego",
    items: [
      {
        id: "i1",
        quantity: 3,
        name: "Nuggets de pollo",
        modifiers: ["Salsa BBQ aparte"],
      },
      { id: "i2", quantity: 2, name: "Aros de cebolla" },
    ],
    importantNote: "Sin maní, cliente alérgico.",
    timeline: [
      { time: "09:47", titleKey: "eventReceived", channel: "delivery" },
      { time: "09:50", titleKey: "eventAssigned", actor: "Freidora" },
      { time: "09:52", titleKey: "eventStarted", actor: "Diego" },
      { time: "10:07", titleKey: "eventDelayed" },
    ],
  },
  {
    id: "ko-1045",
    number: "#1045",
    status: "waiting",
    priority: "normal",
    channel: "web",
    station: "bar",
    customerName: "Lucía Paredes",
    elapsedMinutes: 11,
    slaMinutes: 15,
    receivedAt: "10:04",
    assignedTo: "Tomás",
    isPaused: true,
    items: [
      { id: "i1", quantity: 2, name: "Gin Tonic Bocao" },
      { id: "i2", quantity: 1, name: "Pisco sour" },
    ],
    timeline: [
      { time: "10:04", titleKey: "eventReceived", channel: "web" },
      { time: "10:06", titleKey: "eventAssigned", actor: "Bar" },
      { time: "10:08", titleKey: "eventStarted", actor: "Tomás" },
      { time: "10:10", titleKey: "eventPaused", actor: "Tomás" },
    ],
  },
  {
    id: "ko-1046",
    number: "#1046",
    status: "ready",
    priority: "normal",
    channel: "pickup",
    station: "grill",
    customerName: "Felipe Soto",
    elapsedMinutes: 16,
    slaMinutes: 18,
    receivedAt: "09:59",
    assignedTo: "Camila",
    items: [
      {
        id: "i1",
        quantity: 1,
        name: "Sándwich de lomo",
        allergens: ["Gluten", "Lácteos"],
      },
    ],
    timeline: [
      { time: "09:59", titleKey: "eventReceived", channel: "pickup" },
      { time: "10:01", titleKey: "eventAssigned", actor: "Parrilla" },
      { time: "10:03", titleKey: "eventStarted", actor: "Camila" },
      { time: "10:15", titleKey: "eventReady", actor: "Camila" },
    ],
  },
  {
    id: "ko-1047",
    number: "#1047",
    status: "in_preparation",
    priority: "urgent",
    channel: "table",
    station: "grill",
    tableNumber: "3",
    elapsedMinutes: 19,
    slaMinutes: 18,
    receivedAt: "09:56",
    assignedTo: "Camila",
    items: [
      { id: "i1", quantity: 1, name: "Ribeye 300g", modifiers: ["Término medio"] },
      { id: "i2", quantity: 1, name: "Ensalada César" },
    ],
    timeline: [
      { time: "09:56", titleKey: "eventReceived", channel: "table" },
      { time: "09:58", titleKey: "eventAssigned", actor: "Parrilla" },
      { time: "10:00", titleKey: "eventStarted", actor: "Camila" },
      { time: "10:15", titleKey: "eventDelayed" },
    ],
  },
  {
    id: "ko-1048",
    number: "#1048",
    status: "received",
    priority: "high",
    channel: "whatsapp",
    station: "fryer",
    customerName: "Carolina M.",
    elapsedMinutes: 5,
    slaMinutes: 20,
    receivedAt: "10:10",
    items: [
      { id: "i1", quantity: 2, name: "Papas grandes" },
      { id: "i2", quantity: 1, name: "Alitas BBQ x8" },
    ],
    kitchenNotes: "Coordinar salida con papas de #1042.",
    timeline: [{ time: "10:10", titleKey: "eventReceived", channel: "whatsapp" }],
  },
  {
    id: "ko-1049",
    number: "#1049",
    status: "in_preparation",
    priority: "normal",
    channel: "delivery",
    station: "sushi",
    customerName: "Pedro N.",
    elapsedMinutes: 12,
    slaMinutes: 25,
    receivedAt: "10:03",
    assignedTo: "Yuki",
    items: [
      {
        id: "i1",
        quantity: 1,
        name: "Poke bowl salmón",
        modifiers: ["Sin aguacate"],
        allergens: ["Pescado", "Sésamo"],
      },
    ],
    timeline: [
      { time: "10:03", titleKey: "eventReceived", channel: "delivery" },
      { time: "10:05", titleKey: "eventAssigned", actor: "Sushi" },
      { time: "10:07", titleKey: "eventStarted", actor: "Yuki" },
    ],
  },
  {
    id: "ko-1050",
    number: "#1050",
    status: "ready",
    priority: "normal",
    channel: "table",
    station: "desserts",
    tableNumber: "12",
    elapsedMinutes: 8,
    slaMinutes: 12,
    receivedAt: "10:07",
    assignedTo: "Paula",
    items: [
      {
        id: "i1",
        quantity: 2,
        name: "Brownie con helado",
        allergens: ["Gluten", "Lácteos", "Huevo"],
      },
    ],
    timeline: [
      { time: "10:07", titleKey: "eventReceived", channel: "table" },
      { time: "10:08", titleKey: "eventAssigned", actor: "Postres" },
      { time: "10:09", titleKey: "eventStarted", actor: "Paula" },
      { time: "10:15", titleKey: "eventReady", actor: "Paula" },
    ],
  },
  {
    id: "ko-1051",
    number: "#1051",
    status: "delivered",
    priority: "normal",
    channel: "delivery",
    station: "delivery_station",
    customerName: "Rappi · #8821",
    elapsedMinutes: 22,
    slaMinutes: 30,
    receivedAt: "09:53",
    assignedTo: "Marco",
    items: [
      { id: "i1", quantity: 1, name: "Combo familiar" },
      { id: "i2", quantity: 2, name: "Bebida 500ml" },
    ],
    timeline: [
      { time: "09:53", titleKey: "eventReceived", channel: "delivery" },
      { time: "09:55", titleKey: "eventAssigned", actor: "Delivery" },
      { time: "10:05", titleKey: "eventReady", actor: "Marco" },
      { time: "10:15", titleKey: "eventDelivered", actor: "Repartidor" },
    ],
  },
  {
    id: "ko-1052",
    number: "#1052",
    status: "waiting",
    priority: "high",
    channel: "web",
    station: "bar",
    customerName: "Jorge A.",
    elapsedMinutes: 7,
    slaMinutes: 12,
    receivedAt: "10:08",
    items: [
      { id: "i1", quantity: 3, name: "Cerveza artesanal" },
    ],
    timeline: [
      { time: "10:08", titleKey: "eventReceived", channel: "web" },
      { time: "10:09", titleKey: "eventAssigned", actor: "Bar" },
    ],
  },
  {
    id: "ko-1053",
    number: "#1053",
    status: "in_preparation",
    priority: "normal",
    channel: "pickup",
    station: "fryer",
    customerName: "Sofía L.",
    elapsedMinutes: 9,
    slaMinutes: 18,
    receivedAt: "10:06",
    assignedTo: "Diego",
    items: [
      {
        id: "i1",
        quantity: 1,
        name: "Fish & chips",
        allergens: ["Gluten", "Pescado"],
        modifiers: ["Limón aparte"],
      },
    ],
    importantNote: "Contiene gluten.",
    timeline: [
      { time: "10:06", titleKey: "eventReceived", channel: "pickup" },
      { time: "10:07", titleKey: "eventAssigned", actor: "Freidora" },
      { time: "10:08", titleKey: "eventStarted", actor: "Diego" },
    ],
  },
  {
    id: "ko-1054",
    number: "#1054",
    status: "received",
    priority: "urgent",
    channel: "table",
    station: "grill",
    tableNumber: "1",
    elapsedMinutes: 2,
    slaMinutes: 15,
    receivedAt: "10:13",
    items: [
      { id: "i1", quantity: 4, name: "Entrada alitas picantes" },
      { id: "i2", quantity: 2, name: "Hamburguesa clásica" },
    ],
    kitchenNotes: "Mesa VIP — priorizar entrada.",
    timeline: [{ time: "10:13", titleKey: "eventReceived", channel: "table" }],
  },
  {
    id: "ko-1055",
    number: "#1055",
    status: "ready",
    priority: "normal",
    channel: "whatsapp",
    station: "desserts",
    customerName: "Valentina R.",
    elapsedMinutes: 10,
    slaMinutes: 12,
    receivedAt: "10:05",
    assignedTo: "Paula",
    items: [{ id: "i1", quantity: 1, name: "Cheesecake maracuyá" }],
    timeline: [
      { time: "10:05", titleKey: "eventReceived", channel: "whatsapp" },
      { time: "10:06", titleKey: "eventAssigned", actor: "Postres" },
      { time: "10:08", titleKey: "eventStarted", actor: "Paula" },
      { time: "10:15", titleKey: "eventReady", actor: "Paula" },
    ],
  },
];

export const KITCHEN_MOCK_INSIGHTS = [
  "La estación Parrilla está acumulando más retrasos.",
  "El tiempo promedio subió 11% en la última hora.",
  "Hay 4 pedidos con papas esperando coordinación.",
  "Sugiere mover 2 tickets a Freidora.",
] as const;
