import { getTranslations } from "next-intl/server";
import type { NewOrderLabels } from "@/components/dashboard/orders/new/types";

export async function getNewOrderLabels(): Promise<NewOrderLabels> {
  const t = await getTranslations("dashboard.orders.new");
  const tCommon = await getTranslations("common");
  const tChannels = await getTranslations("dashboard.orders.channels");

  return {
    optional: tCommon("optional"),
    required: tCommon("required"),
    header: {
      title: t("header.title"),
      subtitle: t("header.subtitle"),
    },
    breadcrumb: {
      orders: t("breadcrumb.orders"),
      new: t("breadcrumb.new"),
    },
    actions: {
      back: t("actions.back"),
      submit: t("actions.submit"),
      submitting: t("actions.submitting"),
      addItem: t("actions.addItem"),
      removeItem: t("actions.removeItem"),
      addCustomer: t("actions.addCustomer"),
      removeCustomer: t("actions.removeCustomer"),
    },
    customer: {
      title: t("customer.title"),
      description: t("customer.description"),
      name: t("customer.name"),
      namePlaceholder: t("customer.namePlaceholder"),
      phone: t("customer.phone"),
      phonePlaceholder: t("customer.phonePlaceholder"),
      email: t("customer.email"),
      emailPlaceholder: t("customer.emailPlaceholder"),
      documentId: t("customer.documentId"),
      documentIdPlaceholder: t("customer.documentIdPlaceholder"),
      address: t("customer.address"),
      addressPlaceholder: t("customer.addressPlaceholder"),
      notes: t("customer.notes"),
      notesPlaceholder: t("customer.notesPlaceholder"),
      searchPlaceholder: t("customer.searchPlaceholder"),
      noResults: t("customer.noResults"),
      selectedHint: t("customer.selectedHint"),
      selectedTitle: t("customer.selectedTitle"),
      emptySelection: t("customer.emptySelection"),
      picker: {
        title: t("customer.picker.title"),
        description: t("customer.picker.description"),
        addCustomer: t("customer.picker.addCustomer"),
        addSuccess: t("customer.picker.addSuccess"),
      },
    },
    table: {
      title: t("table.title"),
      description: t("table.description"),
      number: t("table.number"),
      numberPlaceholder: t("table.numberPlaceholder"),
      pickerHint: t("table.pickerHint"),
      pickerFree: t("table.pickerFree"),
      pickerOccupied: t("table.pickerOccupied"),
      pickerSelected: t("table.pickerSelected"),
      configureFloorPlan: t("table.configureFloorPlan"),
    },
    channel: {
      title: t("channel.title"),
      description: t("channel.description"),
      label: t("channel.label"),
    },
    items: {
      title: t("items.title"),
      description: t("items.description"),
      menuLabel: t("items.menuLabel"),
      menuPlaceholder: t("items.menuPlaceholder"),
      quantity: t("items.quantity"),
      price: t("items.price"),
      lineTotal: t("items.lineTotal"),
      empty: t("items.empty"),
      emptyDescription: t("items.emptyDescription"),
      photos: t("items.photos"),
      picker: {
        title: t("items.picker.title"),
        description: t("items.picker.description"),
        addProduct: t("items.picker.addProduct"),
        customProduct: t("items.picker.customProduct"),
        emptyMenuTitle: t("items.picker.emptyMenuTitle"),
        emptyMenuDescription: t("items.picker.emptyMenuDescription"),
        footerHint: t("items.picker.footerHint"),
        customProductTitle: t("items.picker.customProductTitle"),
        customProductDescription: t("items.picker.customProductDescription"),
        customNameLabel: t("items.picker.customNameLabel"),
        customNamePlaceholder: t("items.picker.customNamePlaceholder"),
        customPriceLabel: t("items.picker.customPriceLabel"),
        customQuantityLabel: t("items.picker.customQuantityLabel"),
        addCustomSuccess: t("items.picker.addCustomSuccess"),
        hasFlow: t("items.picker.hasFlow"),
      },
      customization: t("items.customization"),
    },
    flowWizard: {
      title: t("flowWizard.title"),
      description: t.raw("flowWizard.description"),
      stepOf: t.raw("flowWizard.stepOf"),
      back: t("flowWizard.back"),
      next: t("flowWizard.next"),
      confirm: t("flowWizard.confirm"),
      cancel: t("flowWizard.cancel"),
      required: t("flowWizard.required"),
      optional: t("flowWizard.optional"),
      quantity: t("flowWizard.quantity"),
      upsellAccept: t("flowWizard.upsellAccept"),
      upsellDecline: t("flowWizard.upsellDecline"),
      total: t("flowWizard.total"),
      validationError: t("flowWizard.validationError"),
    },
    photos: {
      addPhoto: t("photos.addPhoto"),
      removePhoto: t("photos.removePhoto"),
      uploading: t("photos.uploading"),
      uploadError: t("photos.uploadError"),
      invalidImageType: t("photos.invalidImageType"),
      imageTooLarge: t("photos.imageTooLarge"),
      storageNotConfigured: t("photos.storageNotConfigured"),
      moveEarlier: t("photos.moveEarlier"),
      moveLater: t("photos.moveLater"),
      photoSortOrder: t.raw("photos.photoSortOrder"),
    },
    notes: {
      title: t("notes.title"),
      description: t("notes.description"),
      placeholder: t("notes.placeholder"),
    },
    summary: {
      title: t("summary.title"),
      subtotal: t("summary.subtotal"),
      taxes: t("summary.taxes"),
      total: t("summary.total"),
      taxNote: t("summary.taxNote"),
    },
    channels: {
      whatsapp: tChannels("whatsapp"),
      web: tChannels("web"),
      dineIn: tChannels("dineIn"),
      uberEats: tChannels("uberEats"),
      rappi: tChannels("rappi"),
    },
    validation: {
      customers: t("validation.customers"),
      tableNumber: t("validation.tableNumber"),
      draftCustomerName: t("validation.draftCustomerName"),
      items: t("validation.items"),
      itemName: t("validation.itemName"),
      itemPrice: t("validation.itemPrice"),
      itemQuantity: t("validation.itemQuantity"),
    },
    feedback: {
      success: t("feedback.success"),
      error: t("feedback.error"),
    },
    permissions: {
      deniedTitle: t("permissions.deniedTitle"),
      deniedDescription: t("permissions.deniedDescription"),
    },
  };
}
