import type { Order } from "@/lib/orders/types";

export const seedOrders: Order[] = [
  {
    id: "#1042",
    customerName: "Valentina Rojas",
    phone: "+56 9 8421 3344",
    channel: "whatsapp",
    status: "preparing",
    total: "$42.900",
    createdAt: "10:01",
    waitMinutes: 24,
    owner: "Camila",
    history: "14 pedidos previos · ticket alto",
    notes: "Sin cebolla. Confirmar despacho por WhatsApp antes de salir.",
    items: [
      { name: "Bocao Burger", quantity: 2, price: "$25.800" },
      { name: "Papas rusticas", quantity: 1, price: "$6.900" },
      { name: "Limonada menta", quantity: 2, price: "$10.200" },
    ],
    summary: {
      subtotal: "$36.050",
      taxes: "$6.850",
      total: "$42.900",
    },
    timeline: [
      { time: "10:01", titleKey: "eventReceived" },
      { time: "10:03", titleKey: "eventConfirmedAi", actor: "Bocao AI" },
      { time: "10:07", titleKey: "eventPreparing", actor: "Camila" },
    ],
  },
  {
    id: "#1041",
    customerName: "Diego Fuentes",
    phone: "+56 9 1122 9081",
    channel: "web",
    status: "ready",
    total: "$28.500",
    createdAt: "09:54",
    waitMinutes: 31,
    owner: "Nicolas",
    history: "Primera compra · retiro en local",
    notes: "Cliente espera en barra.",
    items: [
      { name: "Ensalada Cesar", quantity: 1, price: "$12.900" },
      { name: "Wrap pollo grill", quantity: 1, price: "$15.600" },
    ],
    summary: {
      subtotal: "$23.950",
      taxes: "$4.550",
      total: "$28.500",
    },
    timeline: [
      { time: "09:54", titleKey: "eventReceived" },
      { time: "09:56", titleKey: "eventConfirmedAi", actor: "Bocao AI" },
      { time: "10:02", titleKey: "eventPreparing", actor: "Nicolas" },
      { time: "10:19", titleKey: "eventReady", actor: "Cocina" },
    ],
  },
  {
    id: "#1040",
    customerName: "Mesa 12",
    phone: "Salon",
    channel: "dineIn",
    status: "confirmed",
    total: "$64.200",
    createdAt: "09:47",
    waitMinutes: 11,
    owner: "Sofia",
    history: "Servicio en salon · 4 personas",
    notes: "Enviar postres cuando cocina libere comanda principal.",
    items: [
      { name: "Tabla para compartir", quantity: 1, price: "$32.900" },
      { name: "Pisco sour", quantity: 4, price: "$31.300" },
    ],
    summary: {
      subtotal: "$53.950",
      taxes: "$10.250",
      total: "$64.200",
    },
    timeline: [
      { time: "09:47", titleKey: "eventReceived" },
      { time: "09:49", titleKey: "eventConfirmedAi", actor: "Sofia" },
    ],
  },
  {
    id: "#1039",
    customerName: "Martin Silva",
    phone: "+56 9 5532 7711",
    channel: "uberEats",
    status: "received",
    total: "$35.700",
    createdAt: "09:42",
    waitMinutes: 6,
    owner: "Ignacio",
    history: "Delivery marketplace",
    notes: "Courier estimado 10:18.",
    items: [
      { name: "Pizza prosciutto", quantity: 1, price: "$22.900" },
      { name: "Tiramisu", quantity: 1, price: "$12.800" },
    ],
    summary: {
      subtotal: "$30.000",
      taxes: "$5.700",
      total: "$35.700",
    },
    timeline: [{ time: "09:42", titleKey: "eventReceived" }],
  },
  {
    id: "#1038",
    customerName: "Antonia Perez",
    phone: "+56 9 7744 1900",
    channel: "rappi",
    status: "delivered",
    total: "$19.900",
    createdAt: "09:20",
    waitMinutes: 43,
    owner: "Camila",
    history: "Cliente frecuente · 8 pedidos",
    notes: "Entrega completada sin incidentes.",
    items: [{ name: "Menu ejecutivo", quantity: 1, price: "$19.900" }],
    summary: {
      subtotal: "$16.730",
      taxes: "$3.170",
      total: "$19.900",
    },
    timeline: [
      { time: "09:20", titleKey: "eventReceived" },
      { time: "09:22", titleKey: "eventConfirmedAi", actor: "Bocao AI" },
      { time: "09:30", titleKey: "eventPreparing", actor: "Camila" },
      { time: "09:44", titleKey: "eventReady", actor: "Cocina" },
      { time: "10:03", titleKey: "eventDelivered", actor: "Rappi" },
    ],
  },
  {
    id: "#1037",
    customerName: "Josefa Lara",
    phone: "+56 9 6651 8892",
    channel: "whatsapp",
    status: "cancelled",
    total: "$51.400",
    createdAt: "09:12",
    waitMinutes: 8,
    owner: "Nicolas",
    history: "Cancelado por cambio de direccion",
    notes: "Cliente pidio reintentar mas tarde.",
    items: [
      { name: "Ramen miso", quantity: 2, price: "$37.800" },
      { name: "Gyozas", quantity: 1, price: "$13.600" },
    ],
    summary: {
      subtotal: "$43.200",
      taxes: "$8.200",
      total: "$51.400",
    },
    timeline: [
      { time: "09:12", titleKey: "eventReceived" },
      { time: "09:14", titleKey: "eventConfirmedAi", actor: "Bocao AI" },
    ],
  },
];

export const demoRestaurantNames = ["Bocao Providencia", "Bocao Vitacura"];
