import { dehydrate, HydrationBoundary } from "@tanstack/react-query";
import { getTranslations } from "next-intl/server";
import { CustomersPageClient } from "@/components/dashboard/customers/customers-page-client";
import type {
  CustomerSegmentLabelMap,
  CustomersLabels,
} from "@/components/dashboard/customers/types";
import { getDashboardContext } from "@/lib/dashboard/context";
import { parseCustomersListSearchParams } from "@/lib/customers/filters";
import { listCustomers } from "@/lib/customers/repository";
import { loadCustomersPageData } from "@/lib/customers/server";
import { getQueryClient } from "@/lib/query/get-query-client";
import { customersPageQueryOptions } from "@/lib/query/customers/customers.queries";
import { searchParamsToRecord } from "@/lib/list-url";

type CustomersPageProps = {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
};

export default async function CustomersPage({
  searchParams,
}: CustomersPageProps) {
  const t = await getTranslations("dashboard.customers");
  const tCommon = await getTranslations("common");
  const context = await getDashboardContext();
  const restaurantId = context?.activeRestaurant?.id ?? "";
  const organizationId = context?.organization.id ?? "";
  const queryClient = getQueryClient();
  const resolvedSearchParams = searchParamsToRecord(await searchParams);
  const filters = parseCustomersListSearchParams(resolvedSearchParams);
  const customerOptions = restaurantId ? await listCustomers(restaurantId) : [];

  if (restaurantId && context) {
    await queryClient.prefetchQuery({
      ...customersPageQueryOptions(restaurantId, filters),
      queryFn: () => loadCustomersPageData(restaurantId, filters, context),
    });
  }

  const segmentLabels: CustomerSegmentLabelMap = {
    vip: t("segments.vip"),
    frequent: t("segments.frequent"),
    new: t("segments.new"),
    inactive: t("segments.inactive"),
    at_risk: t("segments.atRisk"),
    whatsapp: t("segments.whatsapp"),
    high_value: t("segments.highValue"),
  };

  const labels: CustomersLabels = {
    header: {
      title: t("header.title"),
      subtitle: t("header.subtitle"),
    },
    actions: {
      newCustomer: t("actions.newCustomer"),
      importCsv: t("actions.importCsv"),
      export: t("actions.export"),
      createCampaign: t("actions.createCampaign"),
      viewProfile: t("actions.viewProfile"),
      edit: t("actions.edit"),
      addTag: t("actions.addTag"),
      archive: t("actions.archive"),
      delete: t("actions.delete"),
      editProfile: t("actions.editProfile"),
      sendWhatsapp: t("actions.sendWhatsapp"),
      addNote: t("actions.addNote"),
      viewCustomers: t("actions.viewCustomers"),
      suggestedCampaign: t("actions.suggestedCampaign"),
      clearFilters: t("actions.clearFilters"),
      exportSuccess: t("actions.exportSuccess"),
      exportEmpty: t("actions.exportEmpty"),
      comingSoon: t("actions.comingSoon"),
    },
    kpis: {
      total: t("kpis.total"),
      frequent: t("kpis.frequent"),
      averageTicket: t("kpis.averageTicket"),
      inactive: t("kpis.inactive"),
      notAvailable: t("kpis.notAvailable"),
    },
    toolbar: {
      search: t("toolbar.search"),
      searchPlaceholder: t("toolbar.searchPlaceholder"),
      segment: t("toolbar.segment"),
      channel: t("toolbar.channel"),
      sort: t("toolbar.sort"),
      filters: t("toolbar.filters"),
    },
    segments: {
      all: t("segments.all"),
      vip: t("segments.vip"),
      frequent: t("segments.frequent"),
      new: t("segments.new"),
      inactive: t("segments.inactive"),
      atRisk: t("segments.atRisk"),
      whatsapp: t("segments.whatsapp"),
      highValue: t("segments.highValue"),
      cards: {
        vip: {
          name: t("segments.cards.vip.name"),
          description: t("segments.cards.vip.description"),
        },
        frequent: {
          name: t("segments.cards.frequent.name"),
          description: t("segments.cards.frequent.description"),
        },
        new: {
          name: t("segments.cards.new.name"),
          description: t("segments.cards.new.description"),
        },
        inactive: {
          name: t("segments.cards.inactive.name"),
          description: t("segments.cards.inactive.description"),
        },
        atRisk: {
          name: t("segments.cards.atRisk.name"),
          description: t("segments.cards.atRisk.description"),
        },
        whatsapp: {
          name: t("segments.cards.whatsapp.name"),
          description: t("segments.cards.whatsapp.description"),
        },
        highValue: {
          name: t("segments.cards.highValue.name"),
          description: t("segments.cards.highValue.description"),
        },
        reservationFrequent: {
          name: t("segments.cards.reservationFrequent.name"),
          description: t("segments.cards.reservationFrequent.description"),
        },
      },
    },
    channels: {
      all: t("channels.all"),
      whatsapp: t("channels.whatsapp"),
      web: t("channels.web"),
      in_person: t("channels.inPerson"),
      delivery: t("channels.delivery"),
      reservation: t("channels.reservation"),
    },
    sort: {
      last_visit: t("sort.lastVisit"),
      total_spend: t("sort.totalSpend"),
      order_count: t("sort.orderCount"),
      name: t("sort.name"),
      created_at: t("sort.createdAt"),
    },
    tabs: {
      customers: t("tabs.customers"),
      segments: t("tabs.segments"),
      activity: t("tabs.activity"),
    },
    table: {
      customer: t("table.customer"),
      contact: t("table.contact"),
      segment: t("table.segment"),
      orders: t("table.orders"),
      totalSpend: t("table.totalSpend"),
      averageTicket: t("table.averageTicket"),
      lastVisit: t("table.lastVisit"),
      channel: t("table.channel"),
      actions: t("table.actions"),
    },
    drawer: {
      title: t("drawer.title"),
      description: t("drawer.description"),
      profile: t("drawer.profile"),
      metrics: t("drawer.metrics"),
      preferences: t("drawer.preferences"),
      history: t("drawer.history"),
      name: t("drawer.name"),
      phone: t("drawer.phone"),
      email: t("drawer.email"),
      channel: t("drawer.channel"),
      createdAt: t("drawer.createdAt"),
      lastVisit: t("drawer.lastVisit"),
      orders: t("drawer.orders"),
      reservations: t("drawer.reservations"),
      totalSpend: t("drawer.totalSpend"),
      averageTicket: t("drawer.averageTicket"),
      frequency: t("drawer.frequency"),
      favoriteDishes: t("drawer.favoriteDishes"),
      notes: t("drawer.notes"),
      allergies: t("drawer.allergies"),
      tags: t("drawer.tags"),
      noNotes: t("drawer.noNotes"),
      noAllergies: t("drawer.noAllergies"),
      noTags: t("drawer.noTags"),
      noFavoriteDishes: t("drawer.noFavoriteDishes"),
      frequencyLevels: {
        high: t("drawer.frequencyLevels.high"),
        medium: t("drawer.frequencyLevels.medium"),
        low: t("drawer.frequencyLevels.low"),
        none: t("drawer.frequencyLevels.none"),
      },
      tabs: {
        orders: t("drawer.tabs.orders"),
        reservations: t("drawer.tabs.reservations"),
        activity: t("drawer.tabs.activity"),
        notes: t("drawer.tabs.notes"),
      },
    },
    insights: {
      title: t("insights.title"),
      subtitle: t("insights.subtitle"),
    },
    activity: {
      title: t("activity.title"),
      subtitle: t("activity.subtitle"),
      order: t.raw("activity.order"),
      reservation: t.raw("activity.reservation"),
      inactive: t.raw("activity.inactive"),
      markedVip: t.raw("activity.markedVip"),
      tagAdded: t.raw("activity.tagAdded"),
      noteAdded: t.raw("activity.noteAdded"),
    },
    empty: {
      title: t("empty.title"),
      description: t("empty.description"),
      cta: t("empty.cta"),
    },
    bulkActions: {
      selectedCount: t.raw("bulkActions.selectedCount"),
      clearSelection: t("bulkActions.clearSelection"),
      export: t("bulkActions.export"),
      createCampaign: t("bulkActions.createCampaign"),
      saveToSegment: t("bulkActions.saveToSegment"),
      addTag: t("bulkActions.addTag"),
      removeTag: t("bulkActions.removeTag"),
      archive: t("bulkActions.archive"),
      delete: t("bulkActions.delete"),
    },
    profile: {
      title: t("profile.title"),
      description: t("profile.description"),
      basicInfo: t("profile.basicInfo"),
      metrics: t("profile.metrics"),
      segments: t("profile.segments"),
      tags: t("profile.tags"),
      activityTimeline: t("profile.activityTimeline"),
      recentOrders: t("profile.recentOrders"),
      recentReservations: t("profile.recentReservations"),
      name: t("profile.name"),
      email: t("profile.email"),
      phone: t("profile.phone"),
      birthday: t("profile.birthday"),
      customerSince: t("profile.customerSince"),
      lastVisit: t("profile.lastVisit"),
      preferredLanguage: t("profile.preferredLanguage"),
      notes: t("profile.notes"),
      noNotes: t("profile.noNotes"),
      noTags: t("profile.noTags"),
      noSegments: t("profile.noSegments"),
      notAvailable: t("profile.notAvailable"),
      totalOrders: t("profile.totalOrders"),
      totalSpend: t("profile.totalSpend"),
      averageOrderValue: t("profile.averageOrderValue"),
      lifetimeValue: t("profile.lifetimeValue"),
      lastOrderDate: t("profile.lastOrderDate"),
      reservations: t("profile.reservations"),
      loyaltyPoints: t("profile.loyaltyPoints"),
      primaryChannel: t("profile.primaryChannel"),
      guests: t("profile.guests"),
    },
    tags: {
      label: t("tags.label"),
      searchPlaceholder: t("tags.searchPlaceholder"),
      noResults: t("tags.noResults"),
      createTag: t("tags.createTag"),
      createTagDialog: {
        title: t("tags.createTagDialog.title"),
        name: t("tags.createTagDialog.name"),
        namePlaceholder: t("tags.createTagDialog.namePlaceholder"),
        color: t("tags.createTagDialog.color"),
        create: t("tags.createTagDialog.create"),
        cancel: t("tags.createTagDialog.cancel"),
        nameRequired: t("tags.createTagDialog.nameRequired"),
      },
      bulk: {
        addTitle: t("tags.bulk.addTitle"),
        removeTitle: t("tags.bulk.removeTitle"),
        addDescription: t.raw("tags.bulk.addDescription"),
        removeDescription: t.raw("tags.bulk.removeDescription"),
        tags: t("tags.bulk.tags"),
        searchPlaceholder: t("tags.bulk.searchPlaceholder"),
        noResults: t("tags.bulk.noResults"),
        confirmAdd: t("tags.bulk.confirmAdd"),
        confirmRemove: t("tags.bulk.confirmRemove"),
        cancel: t("tags.bulk.cancel"),
        successAdd: t("tags.bulk.successAdd"),
        successRemove: t("tags.bulk.successRemove"),
        error: t("tags.bulk.error"),
      },
    },
    customerDialog: {
      createTitle: t("customerDialog.createTitle"),
      createDescription: t("customerDialog.createDescription"),
      createButton: t("customerDialog.createButton"),
      editTitle: t("customerDialog.editTitle"),
      editDescription: t("customerDialog.editDescription"),
      editButton: t("customerDialog.editButton"),
      createSuccess: t("customerDialog.createSuccess"),
      editSuccess: t("customerDialog.editSuccess"),
    },
    deleteDialog: {
      title: t("deleteDialog.title"),
      titleBulk: t("deleteDialog.titleBulk"),
      description: t.raw("deleteDialog.description"),
      descriptionBulk: t.raw("deleteDialog.descriptionBulk"),
      confirm: t("deleteDialog.confirm"),
      cancel: t("deleteDialog.cancel"),
      success: t("deleteDialog.success"),
      successBulk: t.raw("deleteDialog.successBulk"),
      error: t("deleteDialog.error"),
    },
    savedSegments: {
      title: t("savedSegments.title"),
      subtitle: t("savedSegments.subtitle"),
      smartTitle: t("savedSegments.smartTitle"),
      smartSubtitle: t("savedSegments.smartSubtitle"),
      create: t("savedSegments.create"),
      createTitle: t("savedSegments.createTitle"),
      createDescription: t("savedSegments.createDescription"),
      saveTitle: t("savedSegments.saveTitle"),
      saveDescription: t.raw("savedSegments.saveDescription"),
      addCustomersTitle: t("savedSegments.addCustomersTitle"),
      addCustomersDescription: t.raw("savedSegments.addCustomersDescription"),
      addCustomersDescriptionFallback: t(
        "savedSegments.addCustomersDescriptionFallback",
      ),
      name: t("savedSegments.name"),
      namePlaceholder: t("savedSegments.namePlaceholder"),
      description: t("savedSegments.description"),
      descriptionPlaceholder: t("savedSegments.descriptionPlaceholder"),
      noDescription: t("savedSegments.noDescription"),
      saveMode: t("savedSegments.saveMode"),
      createNew: t("savedSegments.createNew"),
      addToExisting: t("savedSegments.addToExisting"),
      segment: t("savedSegments.segment"),
      selectSegment: t("savedSegments.selectSegment"),
      search: t("savedSegments.search"),
      searchPlaceholder: t("savedSegments.searchPlaceholder"),
      empty: t("savedSegments.empty"),
      selectedCount: t.raw("savedSegments.selectedCount"),
      selectAllCustomers: t("savedSegments.selectAllCustomers"),
      importCustomer: t("savedSegments.importCustomer"),
      addCustomers: t("savedSegments.addCustomers"),
      cancel: t("savedSegments.cancel"),
      save: t("savedSegments.save"),
      created: t("savedSegments.created"),
      addedToExisting: t("savedSegments.addedToExisting"),
      saveError: t("savedSegments.saveError"),
      nameRequired: t("savedSegments.nameRequired"),
      noCustomersSelected: t("savedSegments.noCustomersSelected"),
    },
    accessibility: {
      openActions: t("accessibility.openActions"),
      openDetails: t("accessibility.openDetails"),
      openFilters: t("accessibility.openFilters"),
      selectCustomer: t.raw("accessibility.selectCustomer"),
      selectAllCustomers: t("accessibility.selectAllCustomers"),
    },
    pagination: {
      previous: tCommon("pagination.previous"),
      next: tCommon("pagination.next"),
      page: tCommon("pagination.page"),
      of: tCommon("pagination.of"),
    },
    formDialog: {
      optional: tCommon("optional"),
      required: tCommon("required"),
      customer: {
        name: t("form.name"),
        namePlaceholder: t("form.namePlaceholder"),
        phone: t("form.phone"),
        phonePlaceholder: t("form.phonePlaceholder"),
        email: t("form.email"),
        emailPlaceholder: t("form.emailPlaceholder"),
        documentId: t("form.documentId"),
        documentIdPlaceholder: t("form.documentIdPlaceholder"),
        address: t("form.address"),
        addressPlaceholder: t("form.addressPlaceholder"),
        notes: t("form.notes"),
        notesPlaceholder: t("form.notesPlaceholder"),
        searchPlaceholder: t("form.searchPlaceholder"),
        noResults: t("form.noResults"),
        selectedHint: t("form.selectedHint"),
        emptySelection: t("form.emptySelection"),
        picker: {
          title: t("form.picker.title"),
          description: t("form.picker.description"),
          addCustomer: t("form.picker.addCustomer"),
          addSuccess: t("form.picker.addSuccess"),
        },
      },
      validation: {
        draftCustomerName: t("validation.draftCustomerName"),
        customers: t("validation.draftCustomerName"),
      },
      actions: {
        addCustomer: t("form.picker.addCustomer"),
        removeCustomer: t("actions.archive"),
      },
      avatar: {
        changePhoto: t("avatar.changePhoto"),
        photoHint: t("avatar.photoHint"),
        photoUrl: t("avatar.photoUrl"),
        photoUrlPlaceholder: t("avatar.photoUrlPlaceholder"),
        invalidImageType: t("avatar.invalidImageType"),
        imageTooLarge: t("avatar.imageTooLarge"),
        uploadError: t("avatar.uploadError"),
      },
    },
    feedback: {
      createError: t("feedback.createError"),
      updateError: t("feedback.updateError"),
      deleteError: t("feedback.deleteError"),
    },
    importCustomers: {
      button: t("importCustomers.button"),
      title: t("importCustomers.title"),
      description: t("importCustomers.description"),
      importMode: t("importCustomers.importMode"),
      reuseFromRestaurants: t("importCustomers.reuseFromRestaurants"),
      importFromFile: t("importCustomers.importFromFile"),
      searchPlaceholder: t("importCustomers.searchPlaceholder"),
      empty: t("importCustomers.empty"),
      error: t("importCustomers.error"),
      loading: t("importCustomers.loading"),
      selectedCount: t.raw("importCustomers.selectedCount"),
      importSelected: t("importCustomers.importSelected"),
      cancel: t("importCustomers.cancel"),
      importedSuccessfully: t("importCustomers.importedSuccessfully"),
      importFailed: t("importCustomers.importFailed"),
      organization: t("importCustomers.organization"),
      restaurant: t("importCustomers.restaurant"),
      customer: t("importCustomers.customer"),
      noCustomersSelected: t("importCustomers.noCustomersSelected"),
      noReusableCustomersFound: t("importCustomers.noReusableCustomersFound"),
      allOrganizations: t("importCustomers.allOrganizations"),
      allRestaurants: t("importCustomers.allRestaurants"),
      uploadFile: t("importCustomers.uploadFile"),
      downloadTemplate: t("importCustomers.downloadTemplate"),
      previewImport: t("importCustomers.previewImport"),
      mapColumns: t("importCustomers.mapColumns"),
      invalidFileFormat: t("importCustomers.invalidFileFormat"),
      invalidRows: t("importCustomers.invalidRows"),
      importConfirmed: t("importCustomers.importConfirmed"),
      importCompleted: t("importCustomers.importCompleted"),
      fileTooLarge: t("importCustomers.fileTooLarge"),
      emptyFile: t("importCustomers.emptyFile"),
      noValidRows: t("importCustomers.noValidRows"),
      dropFileHint: t("importCustomers.dropFileHint"),
      row: t("importCustomers.row"),
      errors: t("importCustomers.errors"),
      validRows: t.raw("importCustomers.validRows"),
      invalidRowsCount: t.raw("importCustomers.invalidRowsCount"),
      confirmImport: t("importCustomers.confirmImport"),
      parsing: t("importCustomers.parsing"),
      importing: t("importCustomers.importing"),
      fields: {
        name: t("importCustomers.fields.name"),
        email: t("importCustomers.fields.email"),
        phone: t("importCustomers.fields.phone"),
        documentId: t("importCustomers.fields.documentId"),
        address: t("importCustomers.fields.address"),
        notes: t("importCustomers.fields.notes"),
        avatar: t("importCustomers.fields.avatar"),
      },
    },
  };

  return (
    <HydrationBoundary state={dehydrate(queryClient)}>
      <CustomersPageClient
        labels={labels}
        segmentLabels={segmentLabels}
        restaurantId={restaurantId}
        organizationId={organizationId}
        customerOptions={customerOptions}
      />
    </HydrationBoundary>
  );
}
